### ISSUE TITLE
The library is not correct. It should have the holes with atleast  9.5mm drill

### ISSUE THREAD

**Issue by dmsherazi** [shimniok/eagle-library#3]
currently its using 8 mm which will never accept the XH series connector.

follow this https://github.com/dmsherazi/Eagle-resources/blob/master/Rembrandt%20Electronics%20-%20JST%20XH%20Connectors%20v1-0.lbr
![capture](https://cloud.githubusercontent.com/assets/6149070/15532422/cf6e7f90-2270-11e6-8008-7eca6878a50f.PNG)

**Comment by shimniok** [comment]
I'm so sorry I missed this issue for years. Man a lot has changed since 2016. Anyway I fixed issues with drill size (1mm), pitch (2.5 instead of 2.54), and part outline dimensions based on the XH datasheet. Thanks for bringing this to my attention.
