### ISSUE TITLE
bt_con-jst-xh Error: Device 07-JST has no footprint!

### ISSUE THREAD

**Issue by satoer** [shimniok/eagle-library#4]
When I try to use 07-JST, eagle comes with this error message:
"Device 07-JST has no footprint!"
Hope you can fix this, this is the only JST XH library I could find with the numbering correct (from right to left).

**Comment by shimniok** [comment]
Sorry this took so long. I added a footprint for 07-JST. I also fixed issues with drill size, pitch, and part outline. Thanks for giving me the heads up.

**Comment by satoer** [comment]
No problem. Thanks for solving!
